### PR TITLE
Textless square version of logos

### PR DESCRIPTION
**Pull request by royemosby**
Created square logo versions for [ Textless Logo Files #6 ](https://github.com/0atman/HumanMadeMark-com/issues/6)

### CODE REVIEW

**Comment by 0atman** [comment]
My goodness, thank you very much! I'll get these up on the site now

**Comment by 0atman** [comment]
This is now live, thank you so much! https://humanmademark.com/

**Comment by royemosby** [comment]
@0atman the Human Made mark is a good premise and I'm glad to support it! I'll be using this too eventually.

**Comment by 0atman** [comment]
oh! Roy, would you like crediting on the website? If so, what name and link would you like?

**Comment by royemosby** [comment]
Nah, no need for credit but I appreciate the offer. Graphics programs make editing SVGs very easy. Anyway, I'm in the commit history, which is good enough for me.

**Comment by 0atman** [comment]
Well thank you!

**Comment by royemosby** [comment]
Very welcome!

**Pull request merged**
